spring.application.name=backend

spring.datasource.url=${DATABASE_URL}
server.port=8080
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Mail Konfiguration für Brevo
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=${BREVO_PORT}
spring.mail.username=${BREVO_SMTP_USER}
spring.mail.password=${BREVO_SMTP_PASSWORD}

# SMTP Auth und StartTLS aktivieren (Wichtig für Brevo!)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

application.security.jwt.secret-key=${JWT_SECRET_KEY}