spring.application.name=backend

spring.datasource.url=jdbc:postgresql://ep-floral-morning-agdcod3a-pooler.c-2.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_nUJDPEzGTZ84&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_nUJDPEzGTZ84
spring.datasource.driver-class-name=org.postgresql.Driver

# 'update' ist perfekt für die Entwicklung: Es erstellt Tabellen automatisch und fügt neue Spalten hinzu, wenn du deine Java-Klassen änderst.
spring.jpa.hibernate.ddl-auto=update

# Sagt Hibernate, dass es mit einer PostgreSQL-Datenbank spricht
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Zeigt dir in der Konsole genau an, welche SQL-Befehle Spring Boot im Hintergrund ausführt
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true