spring.application.name=backend

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# 'update' ist perfekt für die Entwicklung: Es erstellt Tabellen automatisch und fügt neue Spalten hinzu, wenn du deine Java-Klassen änderst.
spring.jpa.hibernate.ddl-auto=validate

# Sagt Hibernate, dass es mit einer PostgreSQL-Datenbank spricht
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway Konfiguration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
