CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    uname VARCHAR(50) NOT NULL UNIQUE,
    fname VARCHAR(50),
    lname VARCHAR(50),
    password_hash VARCHAR(255) NOT NULL,
    mail VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_date TIMESTAMP NOT NULL
    event_desc TEXT,
    event_status VARCHAR(255) NOT NULL,
    event_title VARCHAR(100) NOT NULL,
    event_user_id BIGINT NOT NULL,
    event_loc_id BIGINT,
    CONSTRAINT event_loc_id_fkey FOREIGN KEY (event_loc_id) REFERENCES public.locations (loc_id)
)
